# -*- coding: utf-8 -*-
#: settings for liquidluck

#: site information
#: all variables can be accessed in template with ``site`` namespace.
#: for instance: {{site.name}}
site:
    name: Markus Unterwaditzer
    url: "https://unterwaditzer.net/"

#: this config defined information of your site
#: 1. where the resources  2. how should the site be generated
config:
    source: content
    output: deploy
    static: deploy/static
    static_prefix: /static/
    permalink: "{{date.year}}/{{filename}}.html"
    relative_url: true
    perpage: 30
    feedcount: 20
    timezone: "+01:00"


author:
    default: Markus Unterwaditzer

#: active readers
reader:
    active:
        - liquidluck.readers.restructuredtext.RestructuredTextReader

#: active writers
writer:
    active:
        - liquidluck.writers.core.PostWriter
        - liquidluck.writers.core.PageWriter
        - liquidluck.writers.core.ArchiveWriter
        - liquidluck.writers.core.ArchiveFeedWriter
        - liquidluck.writers.core.FileWriter
        - liquidluck.writers.core.StaticWriter
        - liquidluck.writers.core.YearWriter

#: theme variables
theme:
    name: blargh

    # theme variables are defined by theme creator
    # you can access theme in template with ``theme`` namespace
    # for instance: {{theme.disqus}}
    vars:
        copyright: "© Copyright 2014-2017 by Markus Unterwaditzer. <br/>Content licensed under the <a href=https://creativecommons.org/licenses/by-nc-sa/3.0/>Creative Commons attribution-noncommercial-sharealike License</a>."
        navigation:
            - name: Contact
              link: /contact.html

#: template variables
template:
    vars:
        # key: value
    filters:
        # key: value
