[settings]
caching = true
cache_dir = ".soupault-cache"

# Stop on page processing errors?
strict = true

# Display progress?
verbose = true

# Display detailed debug output?
debug = false

# Where input files (pages and assets) are stored.
site_dir = "site"

# Where the output goes
build_dir = "build"

# Pages will other extensions are considered static assets
# and copied to build/ unchanged
page_file_extensions = ["htm", "html", "md", "rst", "adoc"]

# Files with these extensions are ignored.
ignore_extensions = ["draft"]

# Treat files as content to insert in the template,
# unless they have an <html> element in them.
generator_mode = true
complete_page_selector = "html"

# Use templates/main.html file for the page template.
default_template_file = "templates/main.html"

# The content will be inserted into its <main> element,
# after its last already existing child.
default_content_selector = "main"
default_content_action = "append_child"

# Set the document type to HTML5, unless the page already has
# a doctype declaration.
doctype = "<!DOCTYPE html>"
keep_doctype = true

# Do not indent HTML tags, as it causes whitespace issues in Firefox
# https://github.com/PataphysicalSociety/soupault/issues/46
pretty_print_html = false

clean_urls = false

# Look for plugin files in plugins/
plugin_discovery = true
plugin_dirs = ["plugins"]

[preprocessors]
rst = './bin/pandoc -f rst -t html --no-highlight'
md = './bin/pandoc -f commonmark -t html -fmarkdown-implicit_figures --no-highlight'

[index.fields.title]
selector = ["h1"]

[index.fields.content]
selector = ["main"]

[index.fields.date]
selector = ["time#post-date", "time"]
extract_attribute = "datetime"
fallback_to_content = true

[index]
sort_descending = true
sort_type = "calendar"
sort_by = "date"

date_formats = ["%F"]

[index.views.blog_truncated]
path_regex = "/[0-9]+/"
index_selector = "#blog-index"
index_processor = "scripts/render-index 3"

[index.views.blog_full]
path_regex = "/[0-9]+/"
index_selector = "#blog-index-full"
index_processor = "scripts/render-index"

[widgets.atom]
widget = "atom"
page = "index.md"
feed_file = "feed.xml"

[custom_options]
site_url = "https://unterwaditzer.net"
site_author = "Markus Unterwaditzer"
site_title = "Markus Unterwaditzer"
site_logo = "https://unterwaditzer.net/favicon.ico"

[widgets.canonical]
widget = "preprocess_element"
selector = "link[rel=canonical].placeholder-soupault"
action = "replace_element"

# ignore old html on stdin entirely, set new HTML
command = """
echo '<link rel="canonical" href="https://unterwaditzer.net'$PAGE_URL'">'
"""

# Remove code tags such that we have an easier time passing the data to pygmentize
[widgets.remove-code-tags-in-pre]
widget = "preprocess_element"
selector = "pre"
action = "replace_content"
command = "sed -e 's/<\\/*code>//g'"
parse = false

[widgets.pygmentize]
after = "remove-code-tags-in-pre"
widget = "preprocess_element"
action = "replace_element"
selector = "pre[class^=sourceCode ]"
command = "uv tool run --from pygments==2.16.1 pygmentize -f html -l $(echo $ATTR_CLASS | sed -e 's/sourceCode //g')"

# Re-adding code tags such that firefox reader mode works
[widgets.add-code-tags-to-pre]
after = "pygmentize"
widget = "preprocess_element"
action = "replace_content"
selector = "div.highlight pre"
command = "printf '<code>' && cat && printf '</code>'"

[widgets.set-page-title]
widget = "title"
selector = ["h1:not(#brand)"]
default = "Markus Unterwaditzer"
append = " - Markus Unterwaditzer"

[widgets.remove-home-link]
widget = "delete_element"
selector = ".home-link"
page = "index.md"
