#!/usr/bin/env python3

import sys
import json

items = json.load(sys.stdin)

try:
    limit = int(sys.argv[1])
    items = items[:limit]
except IndexError:
    pass

for item in items:
    print(f"""<li>
<time class=post-date>{item['date']}</time>
<a href="{item['url']}">{item['title']}</a>
</li>
    """)
